name: Reusable workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}

jobs:
  example_job:
    name: Generate output
    # runs-on: ubuntu-latest
    # environment:
    #   name: ${{ needs.set-tag.outputs.environment }}
    # concurrency:
    #   group: switch-traffic-${{ needs.set-tag.outputs.environment }}
    #   cancel-in-progress: true
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - id: step1
        run: echo "firstword=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "secondword=world" >> $GITHUB_OUTPUT
      - name: debug
        run: |
          echo 'github.event_name: ' ${{ github.event_name }}
          echo 'github.ref_name: ' ${{ github.ref_name }}
          echo 'github.base_ref: ' ${{ github.base_ref }}
          cat $GITHUB_EVENT_PATH
