name: Reusable workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    inputs:
      TEST1:
        type: string
        required: true
      TEST2:
        type: string
        required: true
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    concurrency:
      group: concurrency-test
      cancel-in-progress: true
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - id: step1
        run: echo "firstword=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "secondword=world" >> $GITHUB_OUTPUT
      - name: debug
        run: |
          echo 'vars.PROTECTED_REVISION_TAGS: ' ${{ vars.PROTECTED_REVISION_TAGS }}
          echo 'github.event_name: ' ${{ github.event_name }}
          echo 'github.ref_name: ' ${{ github.ref_name }}
          echo 'github.base_ref: ' ${{ github.base_ref }}
          echo 'inputs.TEST1: ' ${{ inputs.TEST1 }}
          echo 'inputs.TEST2: ' ${{ inputs.TEST2 }}
          cat $GITHUB_EVENT_PATH
